//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time_Tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hour
    {
        public int Id { get; set; }
        public int Hours { get; set; }
        public string ModuleDate { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual User User { get; set; }
    }
}
